spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前使用的数据源 druid
    druid:
      initial-size: 2 #初始化连接大小 根据实际情况来
      min-idle: 1 #	池中维护的最小空闲连接数 默认10 根据实际情况来
      max-active: 10 # 池中最大连接数    根据实际情况来
      default-auto-commit: true # 自动提交从池中返回的连接
      test-on-borrow: true #申请连接时执行validationQuery检测连接是否有效。
      max-evictable-idle-time-millis: 1800000 # 最大生存的时间毫秒
      min-evictable-idle-time-millis: 300000  #最小生存的时间毫秒
      validation-query: select 1
      default-read-only: false  # 是否只读
      aop-patterns: zdc.enterprise.service.impl.*.* # 监控切入点
      filter:               #过滤器配置
        stat:
          enabled: true
          merge-sql: true
          slow-sql-millis: 1
      stat-view-servlet:    # 监听配置
        enabled: true              # 是否启用监控
        url-pattern: /druid/*      #访问路径
        reset-enable: false
        login-username: 123123     #访问账号
        login-password: 123123


