server:
  port: 80
spring:
  application:
    name: "zdc"
  devtools:
    restart:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql 8.0
    url: jdbc:mysql:///zdc_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123123
    type: com.zaxxer.hikari.HikariDataSource #当前使用的数据源 Hikari

    ############## hikari 配置 ##############
    hikari:
      minimum-idle: 1 #	池中维护的最小空闲连接数 默认10 根据实际情况来
      maximum-pool-size: 10 # 池中最大连接数    根据实际情况来
      auto-commit: true  # 自动提交从池中返回的连接
      idle-timeout: 600000 # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      max-lifetime: 1800000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL
      connection-timeout: 30000   # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-test-query: select 1
      read-only: false      # 是否是只读
    ############## hikari 配置 ##############


############## mybatis 配置 ##############
mybatis:
  mapper-locations: "classpath:/mappers/*Mapper.xml"
  type-aliases-package: zdc.enterprise.entity
  configuration:
    use-generated-keys: true

############## mybatis 配置 ##############
